-- public.restaurante definition

-- Drop table

-- DROP TABLE public.restaurante;


-- public.localizacao definition

-- Drop table

-- DROP TABLE public.localizacao;

CREATE TABLE public.localizacao (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	latitude float8 NULL,
	longitude float8 NULL,
	CONSTRAINT localizacao_pkey PRIMARY KEY (id)
);


CREATE TABLE public.restaurante (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	cnpj varchar(255) NULL,
	dataatualizacao timestamp NULL,
	datacriacao timestamp NULL,
	nome varchar(255) NULL,
	proprietario varchar(255) NULL,
	localizacao_id int8 NULL,
	CONSTRAINT restaurante_pkey PRIMARY KEY (id)
);


-- public.restaurante foreign keys

ALTER TABLE public.restaurante ADD CONSTRAINT fkdfbggt9ievc4ev74wl3tdnscl FOREIGN KEY (localizacao_id) REFERENCES public.localizacao(id);